version: '3.8'

services:
  frontend:
    build:
      context: ./ecommerce-frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    volumes:
      - frontend_build:/app/build
    environment:
      - REACT_APP_EXPRESS_URL=http://backend:5000
    networks:
      - app-network

  backend:
    build:
      context: ./ecommerce-backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - JWT_SECRET=secret
      - JWT_EXPIRATION=1d
      - PORT=5000
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - frontend_build:/srv:ro
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
      
volumes:
  mongodb_data:
  caddy_data:
  caddy_config:
  frontend_build:

networks:
  app-network:
    driver: bridge